package com.zc.demo_20190419.domain.repository;

import com.zc.demo_20190419.domain.entity.SysPermissionRole;
import com.zc.demo_20190419.domain.entity.SysPermissionRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SysPermissionRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    long countByExample(SysPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    int deleteByExample(SysPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    @Insert({
        "insert into sys_permission_role (id, role_id, ",
        "permission_id)",
        "values (#{id,jdbcType=BIGINT}, #{roleId,jdbcType=BIGINT}, ",
        "#{permissionId,jdbcType=BIGINT})"
    })
    int insert(SysPermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    int insertSelective(SysPermissionRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    List<SysPermissionRole> selectByExample(SysPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysPermissionRole record, @Param("example") SysPermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission_role
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    int updateByExample(@Param("record") SysPermissionRole record, @Param("example") SysPermissionRoleExample example);
}