package com.zc.demo_20190419.domain.repository;

import com.zc.demo_20190419.domain.entity.SysRoleUser;
import com.zc.demo_20190419.domain.entity.SysRoleUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SysRoleUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Mon Apr 22 15:07:14 CST 2019
     */
    long countByExample(SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Mon Apr 22 15:07:14 CST 2019
     */
    int deleteByExample(SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Mon Apr 22 15:07:14 CST 2019
     */
    @Insert({
        "insert into sys_role_user (id, sys_user_id, ",
        "sys_role_id)",
        "values (#{id,jdbcType=BIGINT}, #{sysUserId,jdbcType=BIGINT}, ",
        "#{sysRoleId,jdbcType=BIGINT})"
    })
    int insert(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Mon Apr 22 15:07:14 CST 2019
     */
    int insertSelective(SysRoleUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Mon Apr 22 15:07:14 CST 2019
     */
    List<SysRoleUser> selectByExample(SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Mon Apr 22 15:07:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysRoleUser record, @Param("example") SysRoleUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_user
     *
     * @mbg.generated Mon Apr 22 15:07:14 CST 2019
     */
    int updateByExample(@Param("record") SysRoleUser record, @Param("example") SysRoleUserExample example);
}