package com.zc.demo_20190419.domain.repository;

import com.zc.demo_20190419.domain.entity.SysUser;
import com.zc.demo_20190419.domain.entity.SysUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    long countByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    int deleteByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    @Insert({
        "insert into sys_user (id, username, ",
        "password, email, ",
        "sex, age, createDate, ",
        "loginName, birthday, ",
        "userLevel, bindServer, ",
        "description)",
        "values (#{id,jdbcType=BIGINT}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{sex,jdbcType=BIT}, #{age,jdbcType=INTEGER}, #{createdate,jdbcType=TIMESTAMP}, ",
        "#{loginname,jdbcType=VARCHAR}, #{birthday,jdbcType=DATE}, ",
        "#{userlevel,jdbcType=INTEGER}, #{bindserver,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR})"
    })
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    List<SysUser> selectByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Tue Apr 23 10:49:16 CST 2019
     */
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);
}